### ISSUE TITLE
Restructure LDAP Login to be more seamless

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#71]
The current login structure could use reworking, it is broken out into LDAP and User login. We should reconfigure them so users only have 1 login box.

Related to 3 on https://github.com/mitre/vulcan/issues/70#issuecomment-614083119

Implementation details: https://ognjen.io/devise-ldap-and-database/

## TODO
 - [x] Add a Sign In | Registration tab on top of the sign in form.
 - [x] Finish actually reimplementing LDAP and Local login to work through this single form
 - [x] Redesign Password Reset page as well
 - [x] Get user dropdown in the top right actually working properly
 - [x] Figure out actually useful text for homepage that will benefit a user who does not fully understand what Vulcan does.
 - [x] Add ability to turn local login on or off.

**Comment by rbclark** [comment]
The homepage of the app is now a login page, it now looks as follows:

<img width="1371" alt="Screen Shot 2020-05-11 at 3 51 14 PM" src="https://user-images.githubusercontent.com/2308869/81605326-49797080-939f-11ea-95cc-af15c0734959.png">
 
## TODO
 - [ ] Add a Sign In | Registration tab on top of the sign in form.
 - [ ] Finish actually reimplementing LDAP and Local login to work through this single form
 - [ ] Redesign Password Reset page as well
 - [ ] Get user dropdown in the top right actually working properly
 - [ ] Figure out actually useful text for homepage that will benefit a user who does not fully understand what Vulcan does.

**Comment by rbclark** [comment]
Unfortunately the more I've worked on this the more I've realized that due to time constraints it may be best to stick to 2 login pages for now. In order to improve the design I am adding the ability for users to turn LDAP authentication on and off, and I am also going to add the ability to turn local user registration on and off (aka only allow LDAP users in).

Additionally I've done a lot more research about different LDAP authentication mechanisms with Devise and have come to the conclusion that there are 3 options

https://github.com/cschiewek/devise_ldap_authenticatable (currently in use)
**Pros:**
 - Easy to setup
**Cons:**
 - Requires 2 different user models with devise setup on both to use, which is a huge con since it makes an absolute mess of the routes.
 - Issue discussing adding support for multiple authentication methods on one model has been open for 10 years, so very low chance of that being fixed.

https://github.com/heartcombo/devise/wiki/How-To:-Authenticate-via-LDAP
**Pros:**
 - Can support anything and everything we may ever need.
**Cons:**
 - Requires us to implement anything and everything
 - Docs are 4 years out of date and this doesn't work, there is an answer on the Github issues for Devise on how to fix it but for some reason nobody has bothered to update the wiki. Basically we'd be on our own.

https://gitlab.com/gitlab-org/omniauth-ldap
**Pros:**
 - This is the method that Gitlab uses, which means it will most likely be supported for as long as Gitlab is around.
 - Only requires one user model and one devise model, so it makes data management in the backend a lot easier.
 - Is extremely flexible, easy to add any of the LDAP features that Gitlab currently supports if this is our backend: https://docs.gitlab.com/ee/administration/auth/ldap.html
**Cons:**
 - Due to the layers of features in Gitlab, it is very hard to make sense of what is and isn't required for a simple implementation of this version.
 - Examples of how to use this implementation are very sparse outside of the Gitlab source code. Fortunately the Gitlab source code is extremely in-depth.

Because of all this I've come to the conclusion that it is best that we use the Gitlab solution since it is basically guaranteed to be maintained and supported for as long as Gitlab exists.

**Comment by jrwhite17** [comment]
@rbclark -- I agree with you assessment.

Does the omniauth library enable authentication from GitHub user accounts?

**Comment by rbclark** [comment]
@jrwhite17 That is correct, the omniauth library has an extension that handles Github authentication: https://github.com/omniauth/omniauth-github

**Comment by rbclark** [comment]
<img width="1312" alt="Screen Shot 2020-05-19 at 9 00 03 AM" src="https://user-images.githubusercontent.com/2308869/82381593-7dd0da80-99f8-11ea-88a4-23c08dada4d7.png">
<img width="1312" alt="Screen Shot 2020-05-19 at 9 00 35 AM" src="https://user-images.githubusercontent.com/2308869/82381594-7e697100-99f8-11ea-961b-ef54f70d15d0.png">
<img width="1293" alt="Screen Shot 2020-05-19 at 9 00 56 AM" src="https://user-images.githubusercontent.com/2308869/82381595-7e697100-99f8-11ea-938c-0da8d4fbee49.png">
<img width="1310" alt="Screen Shot 2020-05-19 at 9 01 17 AM" src="https://user-images.githubusercontent.com/2308869/82381596-7f020780-99f8-11ea-873b-e6b049acf4e4.png">
<img width="1310" alt="Screen Shot 2020-05-19 at 9 02 10 AM" src="https://user-images.githubusercontent.com/2308869/82381597-7f020780-99f8-11ea-9eb3-6405daf31be6.png">

Validation of LDAP using the `rroemhild/test-openldap` Docker container

<img width="1901" alt="Screen Shot 2020-05-19 at 9 03 12 AM" src="https://user-images.githubusercontent.com/2308869/82381598-7f9a9e00-99f8-11ea-82ad-61df48ee3b98.png">
<img width="1901" alt="Screen Shot 2020-05-19 at 9 03 32 AM" src="https://user-images.githubusercontent.com/2308869/82381601-7f9a9e00-99f8-11ea-8169-ae29adc28457.png">
